export * from './home';
export * from './about';
export * from './achievements';
export * from './department';
export * from './calculator';
export * from './portfolio';
export * from './contact';
export * from './section/prod';
export * from './section/networkProd';
export * from './section/multimediaProd'
export * from './section/ITsupport'
export * from './section/sectionPlus/customers'
export * from './section/sectionPlus/parteners'
export * from './section/sectionPlus/ApplyForm';
